version: '3'

services:
  frontend:
    build: frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
      - cache
  backend:
    build: backend
    ports:
      - "1337:8080"
  cache:
    build: varnish
    depends_on:
      - backend
    ports:
      - "8080:80"
